version: '3.9'

services:

  pg_db:
    image: postgres:14.3-alpine3.15
    container_name: pg_db
    ports:
      - "5431:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: sheets_base
